config/routes.rb
Rails.application.routes.draw do
  root "items#index"

  resources :items
  resources :warehouses
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/warehouse.rb
class Warehouse < ApplicationRecord
  has_many :items
  
  validates :name, presence: true
  validates :location, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
    @warehouse = Warehouse.find_by(id: @item.warehouse_id)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to root_path, status: :see_other
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])

    if @item.update(item_params)
      redirect_to root_path, status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def item_params
      params.require(:item).permit(:title, :body, :warehouse_id)
    end
end

app/controllers/warehouses_controller.rb
class WarehousesController < ApplicationController
  def index
    @warehouses = Warehouse.all
  end

  def show
    @warehouse = Warehouse.find(params[:id])
  end

  def new
    @warehouse = Warehouse.new
  end

  def create
    @warehouse = Warehouse.new(warehouse_params)

    if @warehouse.save
      redirect_to warehouses_path, status: :see_other
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @warehouse = Warehouse.find(params[:id])
  end

  def update
    @warehouse = Warehouse.find(params[:id])

    if @warehouse.update(warehouse_params)
      redirect_to warehouses_path, status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @warehouse = Warehouse.find(params[:id])
    @warehouse.destroy

    redirect_to warehouses_path, status: :see_other
  end

  private
    def warehouse_params
      params.require(:warehouse).permit(:name, :location)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with model: item do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %><br>
    <% item.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% item.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :warehouse %><br>
    <%= form.collection_select :warehouse_id, Warehouse.order(:name), :id, :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Edit Item in Inventory</h1>

<%= render "form", item: @item %>

app/views/items/index.html.erb
<h1>Inventory Manager, Items:</h1>

<ul>
  <% @items.each do |item| %>
    <li>
      <%= link_to item.title, item %>
    </li>
  <% end %>
</ul>

<%= link_to "Add new item to inventory", new_item_path %> <br>
<%= link_to "View warehouses", warehouses_path %>

app/views/items/new.html.erb
<h1>Add New Item to Inventory</h1>

<%= render "form", item: @item %>

app/views/items/show.html.erb
<h1><%= @item.title %></h1>

<p><%= @item.body %></p>
<% if @warehouse.present? %>
  <p>This product is at the following warehouse: <%= @warehouse.name %> which is located at: <%= @warehouse.location %></p>
<% end %>

<ul>
  <li><%= link_to "Edit Item", edit_item_path(@item) %></li>
  <li><%= link_to "Remove Item", item_path(@item), data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure you wish to remove item?"
  } %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Inventory</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/warehouses/_form.html.erb
<%= form_with model: warehouse do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %><br>
    <% warehouse.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :location %><br>
    <%= form.text_area :location %><br>
    <% warehouse.errors.full_messages_for(:location).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/warehouses/edit.html.erb
<h1>Edit Warehouse</h1>

<%= render "form", warehouse: @warehouse %>

app/views/warehouses/index.html.erb
<h1>Inventory Manager, Warehouses:</h1>

<ul>
  <% @warehouses.each do |warehouse| %>
    <li>
      <%= link_to warehouse.name, warehouse %>
    </li>
  <% end %>
</ul>

<%= link_to "Add new warehouse", new_warehouse_path %> <br>
<%= link_to "View items", items_path %>

app/views/warehouses/new.html.erb
<h1>Add New Warehouse</h1>

<%= render "form", warehouse: @warehouse %>

app/views/warehouses/show.html.erb
<h1><%= @warehouse.name %></h1>

<p><%= @warehouse.location %></p>

<ul>
  <li><%= link_to "Edit Warehouse", edit_warehouse_path(@warehouse) %></li>
  <li><%= link_to "Remove Warehouse", warehouse_path(@warehouse), data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure you wish to remove this warehouse?"
  } %></li>
</ul>